title: Apuntes de guitarra
email: juandiazsuarez0@gmail.com
description: Mis apuntes de guitarra.

baseurl: "/guitar-notes"
url: "https://juandspy.github.io"

heading_anchors: true
search_enabled: true

aux_links:
  "Github repository":
    - "https://github.com/juandspy/guitar-notes"

# Build settings
markdown: kramdown
remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-remote-theme

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/