{
  "theme": "default",
  "htmlLabels": true,
  "securityLevel": "loose"
}

graph TD
    g1[I] -->|1t| g2{II}
    g2 -->|2+1/2t| g5_1[V]
    g5_1 --> sus2(sus2)
  
    g1 -->|2t| g3b{III<sup>b</sup>}
    g3b -->|1+1/2t| g5_2_b[V<sup>b</sup>]
    g5_2_b --> dis(dis)
    g3b -->|2t| g5_2[V]
    g5_2 --> m(m)
    g3b -->|2+1/2t| g5_2_s[V<sup>#</sup>]
    g5_2_s --> m5(m/5<sup>#</sup>)

    g1 -->|2+1/2t| g3{III}
    g3 -->|1t| g5_3_b[V<sup>b</sup>]
    g5_3_b --> Mb5(M/b5)
    g3 -->|1+1/2t| g5_3[V]
    g5_3 --> M(M)
    g3 -->|2t| g5_3_s[V<sup>#</sup>]
    g5_3_s --> aum(aum)

    g1[I] -->|2+1/2t| g4{IV}
    g4 -->|1t| g5_4[V]
    g5_4 --> sus4(sus4)

style sus2 fill:#9cffa2
style m5 fill:#9cffa2
style Mb5 fill:#9cffa2
style sus4 fill:#9cffa2