graph LR
    I --> |1t| II
    II --> |1/2t| III
    III --> |1t| IV
    IV --> |1t| V
    V --> |1/2t| VI
    VI --> |1t| VII
    VII --> |1t| VIII   

    A --> |1t| B
    B --> |1/2t| C
    C --> |1t| D
    D --> |1t| E
    E --> |1/2t| F
    F --> |1t| G
    G --> |1t| A_2[A]   