graph LR
    I --> |1t| II
    II --> |1t| III
    III --> |1/2t| IV
    IV --> |1t| V
    V --> |1t| VI
    VI --> |1t| VII
    VII --> |1/2t| VIII

    C --> |1t| D
    D --> |1t| E
    E --> |1/2t| F
    F --> |1t| G
    G --> |1t| A
    A --> |1t| B
    B --> |1/2t| C_2[C]